######################################################################
# Automatically generated by qmake (3.0) ? 12? 8 03:45:46 2020
######################################################################

TEMPLATE = app
TARGET = ButtonWindow
INCLUDEPATH += .

QT+= widgets


# Input
HEADERS += ButtonWindow.h
SOURCES += ButtonWindow.cpp
