######################################################################
# Automatically generated by qmake (3.0) ? 12? 8 04:17:08 2020
######################################################################

TEMPLATE = app
TARGET = ComboBox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ComboBox.h
SOURCES += ComboBox.cpp
