######################################################################
# Automatically generated by qmake (3.0) ? 12? 8 04:11:10 2020
######################################################################

TEMPLATE = app
TARGET = LineEdit
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += LineEdit.h
SOURCES += LineEdit.cpp
