######################################################################
# Automatically generated by qmake (3.0) ? 12? 8 03:53:27 2020
######################################################################

TEMPLATE = app
TARGET = QBoxLayout
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += LayoutWindow.h
SOURCES += LayoutWindow.cpp
